name: flutter_ai_toolkit_example
description: "Sample apps showing off various features of the Flutter AI Toolkit."
publish_to: 'none'
version: 0.1.3

environment:
  sdk: ^3.4.4

dependencies:
  flutter:
    sdk: flutter
  flutter_ai_toolkit:
    path: ..
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.3
  firebase_core: ^3.4.0
  firebase_vertexai: ^0.2.3
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  gap: ^3.0.1
  go_router: ^14.2.8
  uuid: ^4.5.1
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter_markdown: ^0.7.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recipes_default.json
